data_warehouse_config:
  dw_dbname: "********"
  dw_user: "*******"
  dw_password: "********"
  dw_host: "********"
  dw_port: "****"


hummingbird_config:
  hummingbird_url: ******

email_config:
  email_server: ******

